/**
 * desktop-brand-provision.ts — brand the managed ~/.hermes home for desktop
 * apps without touching Python core defaults.
 *
 * Writes a per-brand skin (branding.agent_name) + SOUL.md identity override
 * so chat replies and /status stop self-identifying as "Hermes Agent". CLI /
 * gateway consumers that don't use this skin keep the default Hermes identity.
 */
import fs from 'node:fs'
import path from 'node:path'

export interface DesktopBrandProvisionInput {
  hermesHome: string
  brandId: string
  productName: string
  sharedSkillsRoot?: string
  /** Optional product URLs / niche for brand-specific SOUL (Foundrly). */
  foundrly?: {
    webUrl?: string
    adminPortalUrl?: string
    adminChatUrl?: string
  }
}

const SHARED_DESKTOP_SKILLS = ['desktop-voice-actions', 'local-first-inference']

function yamlQuote(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

function skinYaml(productName: string): string {
  const slug = productName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')

  return `# Generated by the Hermes desktop app — do not edit the agent_name if
# you want chat identity to stay on-brand. Customize colors freely.
name: ${slug}
description: ${yamlQuote(`${productName} desktop brand`)}

branding:
  agent_name: ${yamlQuote(productName)}
  welcome: ${yamlQuote(`Welcome to ${productName}! Type your message or /help for commands.`)}
  response_label: ${yamlQuote(` ${productName} `)}
  help_header: ${yamlQuote(`${productName} — Available Commands`)}
`
}

/** Thin default used for non-Foundrly brands. */
export function soulMd(productName: string): string {
  return `# ${productName} identity

You are ${productName}, an intelligent AI assistant. You help the user learn, build, and get things done with clarity and care.

- Introduce yourself as "${productName}" when asked who you are.
- Do not call yourself "Hermes Agent" unless the user explicitly asks about the underlying runtime.
`
}

/**
 * Foundrly left-rail identity — aligned with APP_REGISTRY niche in
 * Intelliverse-X-Webfrontend (AI co-founder for small/local businesses).
 */
export function foundrlySoulMd(opts?: {
  webUrl?: string
  adminPortalUrl?: string
  adminChatUrl?: string
}): string {
  const webUrl = opts?.webUrl?.trim() || 'https://getfoundrly.com'
  const adminPortalUrl = opts?.adminPortalUrl?.trim() || 'https://admin.intelli-verse-x.ai/admin/portal'
  const adminChatUrl =
    opts?.adminChatUrl?.trim() || 'https://admin.intelli-verse-x.ai/admin/portal/chat'

  return `# Foundrly identity

You are Foundrly, Intelliverse X's AI co-founder desktop assistant for local and small businesses
(business-building / growth and ops copilot). You run inside the Foundrly desktop app.

When asked who you are or whether you know Foundrly, say yes: you are Foundrly.
Describe Foundrly as an AI co-founder for local/small businesses. Product surfaces include
overnight visibility and growth workflows; Foundrly Home links to the web product and admin portal.

- Product web: ${webUrl}
- Admin portal: ${adminPortalUrl}
- Admin copilot (portal chat, OTP + Foundrly-scoped tools): ${adminChatUrl}
- You are NOT IX Agency (company ops desktop) and NOT QuizVerse (learning).
- Under the hood the runtime is Hermes Agent — mention that only if the user asks about the engine/runtime.
- For Foundrly-scoped admin tools and portal workflows, point users to Foundrly → Admin copilot (portal), not IX Agency.
`
}

/** Normalize for stock-template comparison (CRLF / BOM / trim). */
export function normalizeSoulText(text: string): string {
  return text.replace(/\r\n/g, '\n').replace(/\r/g, '\n').replace(/^\uFEFF/, '').trim()
}

/**
 * True when SOUL.md is missing, empty, or a known stock template we may
 * upgrade — never replace a user-customized persona.
 */
export function shouldWriteBrandSoul(existing: string | null, brandId: string, productName: string): boolean {
  if (existing == null) {
    return true
  }

  const normalized = normalizeSoulText(existing)

  if (!normalized) {
    return true
  }

  const stockThin = normalizeSoulText(soulMd(productName))

  if (normalized === stockThin) {
    return true
  }

  if (brandId !== 'foundrly') {
    return false
  }

  // Already rich Foundrly product identity — leave alone (URLs may vary).
  if (normalized.includes('# Foundrly identity') && normalized.includes('AI co-founder desktop')) {
    return false
  }

  // Stock IX Agency default (shared-home bleed) or thin Foundrly persona → upgrade.
  if (
    normalized.includes('You are IX Agency,') ||
    normalized === normalizeSoulText(soulMd('Foundrly')) ||
    (normalized.includes('You are Foundrly,') && !normalized.includes('AI co-founder'))
  ) {
    return true
  }

  // User-customized SOUL — do not overwrite.
  return false
}

function resolveSoulContents(input: DesktopBrandProvisionInput): string {
  if (input.brandId === 'foundrly') {
    return foundrlySoulMd(input.foundrly)
  }

  return soulMd(input.productName)
}

/** Ensure the active brand skin + SOUL identity exist under HERMES_HOME. Idempotent. */
export function provisionDesktopBrand({
  hermesHome,
  brandId,
  productName,
  sharedSkillsRoot,
  foundrly
}: DesktopBrandProvisionInput): {
  skinPath: string
  soulPath: string
  configTouched: boolean
  soulWritten: boolean
  sharedSkillCount: number
} {
  const home = path.resolve(hermesHome)
  const skinName = `${brandId}-desktop`
  const skinsDir = path.join(home, 'skins')
  const skinPath = path.join(skinsDir, `${skinName}.yaml`)
  const soulPath = path.join(home, 'SOUL.md')
  const configPath = path.join(home, 'config.yaml')
  let sharedSkillCount = 0

  fs.mkdirSync(skinsDir, { recursive: true })
  fs.writeFileSync(skinPath, skinYaml(productName), 'utf8')

  if (sharedSkillsRoot) {
    for (const skill of SHARED_DESKTOP_SKILLS) {
      const source = path.join(sharedSkillsRoot, skill)

      if (!fs.existsSync(path.join(source, 'SKILL.md'))) {
        continue
      }

      const destination = path.join(home, 'skills', skill)
      fs.mkdirSync(destination, { recursive: true })
      fs.cpSync(source, destination, { recursive: true, force: true })
      sharedSkillCount += 1
    }
  }

  let existingSoul: string | null = null

  try {
    existingSoul = fs.readFileSync(soulPath, 'utf8')
  } catch {
    existingSoul = null
  }

  let soulWritten = false

  if (shouldWriteBrandSoul(existingSoul, brandId, productName)) {
    fs.writeFileSync(soulPath, resolveSoulContents({ hermesHome, brandId, productName, foundrly }), 'utf8')
    soulWritten = true
  }

  let configTouched = false
  let configText = ''

  try {
    configText = fs.readFileSync(configPath, 'utf8')
  } catch {
    configText = ''
  }

  const skinLine = `  skin: ${skinName}`

  if (!configText.trim()) {
    fs.writeFileSync(
      configPath,
      `# Generated by the Hermes desktop app — brand provisioning\ndisplay:\n${skinLine}\n`,
      'utf8'
    )
    configTouched = true
  } else if (!/\n\s*skin:\s/m.test(configText) && !/^display:\s*$/m.test(configText)) {
    const block = configText.endsWith('\n') ? `display:\n${skinLine}\n` : `\ndisplay:\n${skinLine}\n`

    fs.appendFileSync(configPath, block, 'utf8')
    configTouched = true
  }

  return { skinPath, soulPath, configTouched, soulWritten, sharedSkillCount }
}
