/**
 * desktop-brand-provision.ts — brand the managed ~/.hermes home for desktop
 * apps without touching Python core defaults.
 *
 * Writes a per-brand skin (branding.agent_name) + SOUL.md identity override
 * so chat replies and /status stop self-identifying as "Hermes Agent". CLI /
 * gateway consumers that don't use this skin keep the default Hermes identity.
 */
import fs from 'node:fs'
import path from 'node:path'

export interface DesktopBrandProvisionInput {
  hermesHome: string
  brandId: string
  productName: string
  sharedSkillsRoot?: string
}

const SHARED_DESKTOP_SKILLS = ['desktop-voice-actions', 'local-first-inference']

function yamlQuote(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

function skinYaml(productName: string): string {
  const slug = productName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')

  return `# Generated by the Hermes desktop app — do not edit the agent_name if
# you want chat identity to stay on-brand. Customize colors freely.
name: ${slug}
description: ${yamlQuote(`${productName} desktop brand`)}

branding:
  agent_name: ${yamlQuote(productName)}
  welcome: ${yamlQuote(`Welcome to ${productName}! Type your message or /help for commands.`)}
  response_label: ${yamlQuote(` ${productName} `)}
  help_header: ${yamlQuote(`${productName} — Available Commands`)}
`
}

function soulMd(productName: string): string {
  return `# ${productName} identity

You are ${productName}, an intelligent AI assistant. You help the user learn, build, and get things done with clarity and care.

- Introduce yourself as "${productName}" when asked who you are.
- Do not call yourself "Hermes Agent" unless the user explicitly asks about the underlying runtime.
`
}

/** Ensure the active brand skin + SOUL identity exist under HERMES_HOME. Idempotent. */
export function provisionDesktopBrand({
  hermesHome,
  brandId,
  productName,
  sharedSkillsRoot
}: DesktopBrandProvisionInput): {
  skinPath: string
  soulPath: string
  configTouched: boolean
  sharedSkillCount: number
} {
  const home = path.resolve(hermesHome)
  const skinName = `${brandId}-desktop`
  const skinsDir = path.join(home, 'skins')
  const skinPath = path.join(skinsDir, `${skinName}.yaml`)
  const soulPath = path.join(home, 'SOUL.md')
  const configPath = path.join(home, 'config.yaml')
  let sharedSkillCount = 0

  fs.mkdirSync(skinsDir, { recursive: true })
  fs.writeFileSync(skinPath, skinYaml(productName), 'utf8')

  if (sharedSkillsRoot) {
    for (const skill of SHARED_DESKTOP_SKILLS) {
      const source = path.join(sharedSkillsRoot, skill)

      if (!fs.existsSync(path.join(source, 'SKILL.md'))) {
        continue
      }

      const destination = path.join(home, 'skills', skill)
      fs.mkdirSync(destination, { recursive: true })
      fs.cpSync(source, destination, { recursive: true, force: true })
      sharedSkillCount += 1
    }
  }

  if (!fs.existsSync(soulPath) || fs.statSync(soulPath).size === 0) {
    fs.writeFileSync(soulPath, soulMd(productName), 'utf8')
  }

  let configTouched = false
  let configText = ''

  try {
    configText = fs.readFileSync(configPath, 'utf8')
  } catch {
    configText = ''
  }

  const skinLine = `  skin: ${skinName}`

  if (!configText.trim()) {
    fs.writeFileSync(
      configPath,
      `# Generated by the Hermes desktop app — brand provisioning\ndisplay:\n${skinLine}\n`,
      'utf8'
    )
    configTouched = true
  } else if (!/\n\s*skin:\s/m.test(configText) && !/^display:\s*$/m.test(configText)) {
    const block = configText.endsWith('\n') ? `display:\n${skinLine}\n` : `\ndisplay:\n${skinLine}\n`

    fs.appendFileSync(configPath, block, 'utf8')
    configTouched = true
  }

  return { skinPath, soulPath, configTouched, sharedSkillCount }
}
