/**
 * Tests for electron/ix-provision.ts — the zero-setup platform wiring:
 * direct EKS MCP entries generated from the registry snapshot, portal
 * skill materialization, and the live LiteLLM model list.
 *
 * Run with: node --test electron/ix-provision.test.ts
 * (Wired into npm test:desktop:platforms in package.json.)
 */

import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'

import {
  fetchLiteLlmModels,
  fullHermesConfigYaml,
  ixDirectMcpServersYaml,
  ixDirectMcpTiles,
  ixExternalSkillDirs,
  materializeIxPortalSkills,
  resetLiteLlmModelsCache,
  tileNeedsBearer
} from './ix-provision'

/* ── direct MCP tile selection ───────────────────────────────────────────── */

test('ixDirectMcpTiles keeps only public HTTPS endpoints on our domains', () => {
  const tiles = ixDirectMcpTiles([
    { id: 'notifuse', mcpUrl: 'https://notifuse-mcp.intelli-verse-x.ai/mcp' },
    { id: 'open-seo', mcpUrl: 'https://seo.toba-tech.ai/mcp' },
    { id: 'quests', mcpUrl: 'http://quests-api.quests-economy.svc.cluster.local:3002/mcp' },
    { id: 'posthog', mcpUrl: 'https://mcp.posthog.com/mcp' },
    { id: 'admin-mcp', mcpUrl: 'https://admin-mcp.intelli-verse-x.ai/' },
    { id: 'no-url' }
  ])

  assert.deepEqual(tiles.map(t => t.id), ['notifuse', 'open-seo'])
})

test('ixDirectMcpTiles drops denylisted broken endpoints even on our domains', () => {
  const tiles = ixDirectMcpTiles([
    // /rpc is the raw Leantime JSON-RPC bridge, not MCP.
    { id: 'leantime', mcpUrl: 'https://leantime-mcp.intelli-verse-x.ai/rpc' },
    // No agent-mcp deployment exists; the hostname 404s via the wildcard ALB.
    { id: 'agent-mcp', mcpUrl: 'https://agent-mcp.intelli-verse-x.ai/mcp' },
    { id: 'notifuse', mcpUrl: 'https://notifuse-mcp.intelli-verse-x.ai/mcp' }
  ])

  assert.deepEqual(tiles.map(t => t.id), ['notifuse'])
})

test('the bundled registry snapshot yields the EKS MCP fleet', () => {
  const ids = ixDirectMcpTiles().map(t => t.id)

  for (const expected of ['notifuse', 'fonoster', 'telnyx', 'chatwoot', 'twenty', 'nakama-console', 'grafana']) {
    assert.ok(ids.includes(expected), `expected ${expected} in ${ids.join(', ')}`)
  }

  assert.ok(!ids.includes('admin-mcp'), 'gateway itself must not be duplicated')
  assert.ok(!ids.includes('leantime'), 'leantime /rpc bridge is not MCP — must stay denylisted')
  assert.ok(!ids.includes('agent-mcp'), 'agent-mcp is not deployed — must stay denylisted')
})

/* ── bearer detection + yaml generation ──────────────────────────────────── */

test('tileNeedsBearer: bearer hints yes, "no token" wrappers no', () => {
  assert.equal(tileNeedsBearer({ id: 'x', mcpAuthHint: 'Bearer = API key' }), true)
  assert.equal(tileNeedsBearer({ id: 'x', mcpAuthHint: 'No token needed; handshake handled by gateway.' }), false)
  assert.equal(tileNeedsBearer({ id: 'x', mcpAuthHint: 'Wrapper MCP, default key.' }), false)
  assert.equal(tileNeedsBearer({ id: 'x' }), false)
})

test('ixDirectMcpServersYaml emits url/timeout and env-var bearer placeholders', () => {
  const yaml = ixDirectMcpServersYaml([
    { id: 'notifuse', label: 'Email', mcpUrl: 'https://notifuse-mcp.intelli-verse-x.ai/mcp', mcpAuthHint: 'Bearer = key' },
    { id: 'intelliverse-mcp', mcpUrl: 'https://mcp.intelli-verse-x.ai/api/mcp', mcpAuthHint: 'Bearer = key' },
    { id: 'grafana', mcpUrl: 'https://grafana-mcp.intelli-verse-x.ai/', mcpAuthHint: 'no token' }
  ])

  assert.match(yaml, /notifuse:\n {4}url: "https:\/\/notifuse-mcp\.intelli-verse-x\.ai\/mcp"\n {4}timeout: 60/)
  assert.match(yaml, /Authorization: "Bearer \$\{NOTIFUSE_MCP_TOKEN\}"/)
  // ids already ending in -mcp must not double up the suffix
  assert.match(yaml, /Authorization: "Bearer \$\{INTELLIVERSE_MCP_TOKEN\}"/)
  // no-token wrappers get no headers block
  assert.ok(!/grafana:[\s\S]*?headers/.test(yaml.split('intelliverse-mcp')[0] + yaml.split('grafana:')[1]))
})

/* ── full generated config ───────────────────────────────────────────────── */

test('fullHermesConfigYaml wires LiteLLM, the gateway and the EKS fleet', () => {
  const yaml = fullHermesConfigYaml('https://litellm.example.com', 'https://gw.example.com/', os.tmpdir())

  assert.match(yaml, /base_url: "https:\/\/litellm\.example\.com\/v1"/)
  assert.match(yaml, /admin-mcp:\n {4}url: "https:\/\/gw\.example\.com\/"/)
  assert.match(yaml, /Authorization: "Bearer \$\{ADMIN_MCP_TOKEN\}"/)

  for (const id of ['notifuse', 'fonoster', 'telnyx']) {
    assert.ok(yaml.includes(`  ${id}:`), `expected direct entry for ${id}`)
  }

  for (const id of ['leantime', 'agent-mcp']) {
    assert.ok(!yaml.includes(`  ${id}:`), `broken endpoint ${id} must not appear in a fresh config`)
  }

  // marker line the init handler uses to know it may regenerate
  assert.match(yaml, /^# Generated by the Hermes desktop/)
})

test('ixExternalSkillDirs falls back to packaged packs when checkouts are absent', () => {
  const fakeHome = fs.mkdtempSync(path.join(os.tmpdir(), 'hermes-home-'))
  const fakeResources = fs.mkdtempSync(path.join(os.tmpdir(), 'hermes-res-'))

  try {
    for (const pack of ['github', 'software-development']) {
      fs.mkdirSync(path.join(fakeResources, 'hermes-skills', pack), { recursive: true })
    }

    // No dev checkouts in the fake home → only the bundled packs qualify.
    const dirs = ixExternalSkillDirs(fakeHome, fakeResources)

    assert.deepEqual(dirs, [
      path.join(fakeResources, 'hermes-skills', 'github'),
      path.join(fakeResources, 'hermes-skills', 'software-development')
    ])

    // A dev checkout shadows its bundled copy.
    fs.mkdirSync(path.join(fakeHome, 'dev/hermes-agent/skills/github'), { recursive: true })

    const withCheckout = ixExternalSkillDirs(fakeHome, fakeResources)

    assert.ok(withCheckout.includes(path.join(fakeHome, 'dev/hermes-agent/skills/github')))
    assert.ok(!withCheckout.includes(path.join(fakeResources, 'hermes-skills', 'github')))

    // Without a resources path (bare node / unpackaged) nothing is invented.
    assert.deepEqual(ixExternalSkillDirs(fakeHome), [path.join(fakeHome, 'dev/hermes-agent/skills/github')])
  } finally {
    fs.rmSync(fakeHome, { recursive: true, force: true })
    fs.rmSync(fakeResources, { recursive: true, force: true })
  }
})

/* ── portal skill materialization ────────────────────────────────────────── */

test('materializeIxPortalSkills writes SKILL.md folders with frontmatter', () => {
  const home = fs.mkdtempSync(path.join(os.tmpdir(), 'hermes-skills-'))

  try {
    const count = materializeIxPortalSkills(home, [
      { id: 'weekly-report', title: 'Weekly report', description: 'Numbers in one place', content: '# Skill\nBody' },
      { id: 'no-content', title: 'Bare', description: 'Description only', persona: 'ops' },
      { id: '///', title: 'bad id' }
    ])

    assert.equal(count, 2)

    const md = fs.readFileSync(path.join(home, 'skills', 'ix-portal', 'weekly-report', 'SKILL.md'), 'utf8')

    assert.match(md, /^---\nname: weekly-report\ndescription: "Numbers in one place"/)
    assert.match(md, /# Skill\nBody/)

    const bare = fs.readFileSync(path.join(home, 'skills', 'ix-portal', 'no-content', 'SKILL.md'), 'utf8')

    assert.match(bare, /persona: "ops"/)
    assert.match(bare, /# Skill: Bare/)
  } finally {
    fs.rmSync(home, { recursive: true, force: true })
  }
})

test('the bundled portal catalog materializes end to end', () => {
  const home = fs.mkdtempSync(path.join(os.tmpdir(), 'hermes-skills-'))

  try {
    const count = materializeIxPortalSkills(home)

    assert.ok(count >= 30, `expected the full catalog, got ${count}`)
  } finally {
    fs.rmSync(home, { recursive: true, force: true })
  }
})

/* ── live LiteLLM models ─────────────────────────────────────────────────── */

test('fetchLiteLlmModels parses /v1/models, sorts, and caches', async () => {
  resetLiteLlmModelsCache()

  let calls = 0

  const fakeFetch = (async (url: string, init: RequestInit) => {
    calls += 1
    assert.equal(url, 'https://llm.example.com/v1/models')
    assert.equal((init.headers as Record<string, string>).Authorization, 'Bearer sk-test')

    return new Response(JSON.stringify({ data: [{ id: 'zeta' }, { id: 'alpha' }, { id: 42 }] }), { status: 200 })
  }) as unknown as typeof fetch

  const models = await fetchLiteLlmModels('https://llm.example.com', 'sk-test', fakeFetch)

  assert.deepEqual(models, [
    { id: 'alpha', label: 'alpha' },
    { id: 'zeta', label: 'zeta' }
  ])

  await fetchLiteLlmModels('https://llm.example.com', 'sk-test', fakeFetch)
  assert.equal(calls, 1, 'second call within TTL must hit the cache')

  resetLiteLlmModelsCache()
})

test('fetchLiteLlmModels returns null on failure or empty base url', async () => {
  resetLiteLlmModelsCache()

  const failing = (async () => new Response('nope', { status: 401 })) as unknown as typeof fetch

  assert.equal(await fetchLiteLlmModels('https://llm.example.com/v1', 'k', failing), null)
  assert.equal(await fetchLiteLlmModels('', 'k', failing), null)

  const throwing = (async () => {
    throw new Error('boom')
  }) as unknown as typeof fetch

  assert.equal(await fetchLiteLlmModels('https://llm.example.com', 'k', throwing), null)

  resetLiteLlmModelsCache()
})
